# Generated by Django 5.1.4 on 2024-12-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_description_en_hotel_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_address_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_address_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='hotelimage',
            name='hotel_video',
            field=models.FileField(blank=True, null=True, upload_to='vid/', verbose_name='Видео'),
        ),
        migrations.AddField(
            model_name='room',
            name='all_inclusive',
            field=models.BooleanField(default=False),
        ),
    ]
