# Generated by Django 5.1.4 on 2024-12-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_room_room_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
